### ISSUE TITLE
Running while the mod is enabled via toggle cause the life and shield and weapon damage reduced

### ISSUE THREAD

**Issue by gameLvr85** [plu5/p-borderlands#5]
Hi,
While using this mod, the issue I am facing is whenever I run while is mod is enable and toggled ON via hotkey, the Health, shield and weapon damage is reduced very much, almost less than half, to reset it, I enable/disable BAR and the values return to normal, and I have to toggle mod off via hotkey, but when I enable mod, the same thing happens, I have to constantly enable/disable BAT to fix the issue. The issue persists even when BAR is enabled, I have to toggle it to reset the values to normal.
After disabling the mod everything is working fine. 
I am using Quite a lot mods, will provide the list if required, Exodus and some blcm QOL mods via constructor mod are enabled.

**Comment by plu5** [comment]
Hi, thank you for the report!

Are you using the latest version of Sprint Adjuster? It sounds like the old Character Class issue (#1) that was fixed in 1.1.0. Changing speed is now done by just modifying the Sprint Definition so it should not be affecting anything else.
