### ISSUE TITLE
Paths status panel always pops up at game start up

### ISSUE THREAD

**Issue by djoole** [plu5/p-borderlands#9]
Hi, first let me thank you for this great mod!

_**On subsequent launches**, the mod will be enabled automatically and save a backup, and no action is required. **The panel will not pop up again** unless there is a problem with the paths. You can open it manually by pressing C in the mod manager._

But the panel always pops up for me.

**Logs :** 
[Saves Backuper] All set
[Python] Python initialized (3)
[Saves Backuper] Preparing backup...
[Saves Backuper] Backup successful! Saved to C:\Users\julba\OneDrive\Documents\My Games\Borderlands The Pre-Sequel\WillowGame\SaveData/backups/SaveData_2024-12-19_19-02-05.zip
[Saves Backuper] Checking if number of backups exceeded threshold...
[Saves Backuper] Threshold not exceeded; no action taken.

**Comment by plu5** [comment]
Hi, thanks for the report. It’s been absolute ages, so I apologise for any annoyance in using this.

I think I identified and fixed the issue. Can you try [latest](https://github.com/plu5/p-borderlands/releases/latest)?

Boring details:
In [mod.py Enable function](https://github.com/plu5/p-borderlands/blob/0794a280c8df016903302a3aad36f4a35b58dc00/SavesBackuper/mod.py#L94), it determines whether to show the dialog based on the values of `self.config.all_set` and `self.ShowConfigOnStartup.CurrentValue`. The latter seemed to be set correctly to `False`, but despite the logs indicating `all_set` is `True`, it was actually initially `False` until *after* the decision to display the dialog. I think the paths were not being loaded from the mod settings [until after config dialog shows](https://github.com/plu5/p-borderlands/blob/0794a280c8df016903302a3aad36f4a35b58dc00/SavesBackuper/configuration.py#L114). [I've changed it](https://github.com/plu5/p-borderlands/commit/1ac738a035e07869686881cbf7fa3019419e950b) to load the paths from mod settings upon enable and before the decision of whether to show the dialog.

**Comment by djoole** [comment]
Thanks for the quick reply and fix, it works perfectly!!
Hats off to you for being still so responsive and active on your mods !
